services:
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "3000:80"
    depends_on:
      auth-service:
        condition: service_healthy
      resume-processor:
        condition: service_healthy
    networks:
      - resume-optimizer

  auth-service:
    build:
      context: ./services/auth
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    env_file:
      - .env.docker
    depends_on: []
    external_links:
      - "host.docker.internal:postgres"
    networks:
      - resume-optimizer
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--output-document=-", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
    restart: unless-stopped

  resume-processor:
    build:
      context: ./services/resume-processor
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    env_file:
      - .env.docker
    depends_on: []
    external_links:
      - "host.docker.internal:postgres"
    networks:
      - resume-optimizer
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--output-document=-", "http://localhost:8081/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
    restart: unless-stopped
    volumes:
      - resume_uploads:/root/uploaded_files

volumes:
  resume_uploads:

networks:
  resume-optimizer:
    driver: bridge