version: '3.8'

services:
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "3000:80"
    depends_on:
      - auth-service
      - resume-processor
    networks:
      - resume-optimizer

  auth-service:
    build:
      context: ./services/auth
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - DATABASE_URL=postgres://postgres:password@postgres:5432/resume_optimizer?sslmode=disable
      - JWT_SECRET=your-jwt-secret
      - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
      - GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET}
    depends_on:
      - postgres
    networks:
      - resume-optimizer

  resume-processor:
    build:
      context: ./services/resume-processor
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    environment:
      - DATABASE_URL=postgres://postgres:password@postgres:5432/resume_optimizer?sslmode=disable
    depends_on:
      - postgres
    networks:
      - resume-optimizer

  postgres:
    image: postgres:15
    environment:
      - POSTGRES_DB=resume_optimizer
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - resume-optimizer

volumes:
  postgres_data:

networks:
  resume-optimizer:
    driver: bridge